#deploy deployer on Rocky
- name: deploy deployer
  hosts: rocky
  become: yes
  vars_prompt:

  - name: password
    prompt: enter your new deployer password
    private: true

  tasks:
    - name: set the password hash fact
      set_fact:
        password_hash: "{{ password | password_hash('sha512') }}"
    - name: create the deployer user if not present
      ansible.builtin.user:
        name: deployer
        state: present
        create_home: yes
        groups: wheel
        append: yes
        password: "{{ password_hash }}"
